import type { Octokit } from "@octokit/rest";
import type { GeneratedFix } from "../ai/schemas.js";
import type { Incident } from "../incidents/types.js";

export async function getRepositoryFiles(
  octokit: Octokit,
  owner: string,
  repo: string,
  ref: string,
  paths: string[],
): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  for (const path of paths) {
    const response = await octokit.repos.getContent({ owner, repo, path, ref });
    if (
      Array.isArray(response.data) ||
      response.data.type !== "file" ||
      !("content" in response.data)
    ) {
      throw new Error(`Expected repository file at ${path}`);
    }
    files[path] = Buffer.from(response.data.content, "base64").toString("utf8");
  }
  return files;
}

export async function createFixPullRequest(
  octokit: Octokit,
  incident: Incident,
  fix: GeneratedFix,
): Promise<{ url: string; branch: string }> {
  const { owner, repository: repo, commitSha } = incident.failure;
  const repository = await octokit.repos.get({ owner, repo });
  const base = repository.data.default_branch;
  const baseRef = await octokit.git.getRef({ owner, repo, ref: `heads/${base}` });
  const branch = `superplane/fix-${commitSha.slice(0, 7)}`;

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseRef.data.object.sha,
  });

  const blobs = await Promise.all(
    fix.changes.map(async (change) => ({
      path: change.path,
      sha: (
        await octokit.git.createBlob({ owner, repo, content: change.newContent, encoding: "utf-8" })
      ).data.sha,
    })),
  );
  const tree = await octokit.git.createTree({
    owner,
    repo,
    base_tree: baseRef.data.object.sha,
    tree: blobs.map((blob) => ({ path: blob.path, mode: "100644", type: "blob", sha: blob.sha })),
  });
  const commit = await octokit.git.createCommit({
    owner,
    repo,
    message: fix.title,
    tree: tree.data.sha,
    parents: [baseRef.data.object.sha],
  });
  await octokit.git.updateRef({ owner, repo, ref: `heads/${branch}`, sha: commit.data.sha });

  const evidence = incident.analysis.evidence.map((item) => `- ${item}`).join("\n");
  const pullRequest = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base,
    title: fix.title || "Fix checkout production configuration",
    body: [
      "## Incident summary",
      incident.analysis.summary,
      "## Likely root cause",
      incident.analysis.likelyRootCause,
      "## Evidence",
      evidence,
      "## Proposed fix",
      fix.description,
      `Original workflow: ${incident.failure.workflowUrl}`,
      "_This fix was generated by the SuperPlane demo after explicit Discord approval. It has not been merged automatically._",
    ].join("\n\n"),
  });
  return { url: pullRequest.data.html_url, branch };
}
